name: MerdoServerPlugin
version: 1.0
main: com.merdo.plugin.MerdoServerPlugin
api-version: 1.13
description: Merdo Launcher VIP Integration
commands:
  login:
    description: Dummy login
  register:
    description: Dummy register
  aurajoin:
    description: Dummy aurajoin
