name: MerdoServerPlugin
version: 1.0
main: com.merdo.plugin.MerdoServerPlugin
api-version: 1.13
depend: [AuthMe, LuckPerms]
description: Merdo Launcher Auth and VIP Integration
commands:
  merdoauth:
    description: Internal command for AuraNW Launcher authentication
    usage: /merdoauth <password>
